name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # Backend
  build-project:
    name: Backend build (SpringBoot)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Quiet Build
        run: mvn -B compile -q

  #Backend Tests
  test-project:
    name: Backend Tests(Mockito)
    needs: build-project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Tests (Quiet Downloads)
        run: >
          mvn -B test 
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.QuietMavenTransferListener=true

  # Frontend
  frontend-check:
    name: Frontend Build (React 19)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'src/main/frontend/package-lock.json'
      - name: Install and Build
        run: |
          npm ci --legacy-peer-deps
          npm run build --if-present